apiVersion: v1
kind: Secret
metadata:
  name: adcs-issuer-secret
  namespace: cert-manager
type: Opaque
stringData:
  password: cGFzc3dvcmQ=
  username: dXNlcm5hbWU=
  # realm: RVhBTVBMRS5DT00= # Required only when authType is kerberos
